'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace WSPersonasServiceReference
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="WSPersonasServiceReference.IWSPersonas")>  _
    Public Interface IWSPersonas
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWSPersonas/Add", ReplyAction:="http://tempuri.org/IWSPersonas/AddResponse")>  _
        Function Add(ByVal nombreCompleto As String, ByVal fechaDeNacimiento As Date, ByVal edad As Byte, ByVal sexo As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWSPersonas/Update", ReplyAction:="http://tempuri.org/IWSPersonas/UpdateResponse")>  _
        Function Update(ByVal personaId As Integer, ByVal nombreCompleto As String, ByVal fechaDeNacimiento As Date, ByVal edad As Byte, ByVal sexo As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWSPersonas/Delete", ReplyAction:="http://tempuri.org/IWSPersonas/DeleteResponse")>  _
        Function Delete(ByVal personaId As Integer) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWSPersonas/GetDataSet", ReplyAction:="http://tempuri.org/IWSPersonas/GetDataSetResponse")>  _
        Function GetDataSet() As System.Data.DataSet
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IWSPersonasChannel
        Inherits WSPersonasServiceReference.IWSPersonas, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class WSPersonasClient
        Inherits System.ServiceModel.ClientBase(Of WSPersonasServiceReference.IWSPersonas)
        Implements WSPersonasServiceReference.IWSPersonas
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function Add(ByVal nombreCompleto As String, ByVal fechaDeNacimiento As Date, ByVal edad As Byte, ByVal sexo As String) As String Implements WSPersonasServiceReference.IWSPersonas.Add
            Return MyBase.Channel.Add(nombreCompleto, fechaDeNacimiento, edad, sexo)
        End Function
        
        Public Function Update(ByVal personaId As Integer, ByVal nombreCompleto As String, ByVal fechaDeNacimiento As Date, ByVal edad As Byte, ByVal sexo As String) As String Implements WSPersonasServiceReference.IWSPersonas.Update
            Return MyBase.Channel.Update(personaId, nombreCompleto, fechaDeNacimiento, edad, sexo)
        End Function
        
        Public Function Delete(ByVal personaId As Integer) As String Implements WSPersonasServiceReference.IWSPersonas.Delete
            Return MyBase.Channel.Delete(personaId)
        End Function
        
        Public Function GetDataSet() As System.Data.DataSet Implements WSPersonasServiceReference.IWSPersonas.GetDataSet
            Return MyBase.Channel.GetDataSet
        End Function
    End Class
End Namespace
